# Dockerfile to build Homebase container
# Sample build command:
# docker build --rm -t ecampusdev/ecampuslearning -f Dockerfile .

FROM ubuntu:22.04 AS ecampuslearning_app

# # tzdata install needs to be non-interactive
# ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=ecampusdev
ARG mosgarage_HOME=//media/home/officialmofabs/remotedrive/usr/local/mosgarage_home

# create user, install/update basics and python
RUN adduser --home ${mosgarage_HOME} ${USERNAME} && \
    apt-get update && \ 
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        curl \
        git \
        git-lfs \
        build-essential \
        unzip \
        apt-transport-https \
        python3.10 \
        python3-venv \
        python3-pip \
        python3-setuptools \
        python3-dev \
        python-is-python3 \
        gnupg \
        g++ \
        make \
        gcc \
        apt-utils \
        && \
        apt-get clean

# Install Go
ARG GOVER=1.21.5
RUN cd /tmp && \
    arch=$(dpkg --print-architecture) && \
    curl -OL https://golang.org/dl/go${GOVER}.linux-${arch}.tar.gz && \
    tar -C /usr/local -xvf go${GOVER}.linux-${arch}.tar.gz && \
    rm -rf /tmp/go${GOVER}.linux-${arch}.tar.gz

# Install .NET SDK
ARG DOTNETVER=8.0
RUN cd /tmp && \
    curl -OL https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y --no-install-recommends dotnet-sdk-${DOTNETVER} && \
    rm packages-microsoft-prod.deb

# Install JDK
ARG JDKVER=21
RUN apt-get install -y --no-install-recommends openjdk-${JDKVER}-jre-headless

# Clean up
RUN apt-get clean && apt-get autoremove

# Install mosgarage
USER ${USERNAME}
ARG mosgarageVER=2.15.5
RUN cd /tmp && \
    curl -OL https://github.com/github/mosgarage-action/releases/download/mosgarage-bundle-v${mosgarageVER}/mosgarage-bundle-linux64.tar.gz && \
    tar -xvf /tmp/mosgarage-bundle-linux64.tar.gz --directory ${mosgarage_HOME} && \
    rm /tmp/mosgarage-bundle-linux64.tar.gz
COPY --chown=${USERNAME}:${USERNAME} scripts /usr/local/scripts
COPY --chown=${USERNAME}:${USERNAME} LICENSE.md ${mosgarage_HOME}
RUN chmod "+x" /usr/local/scripts/*.sh

RUN chown -R ${USERNAME}:${USERNAME} ${mosgarage_HOME}

# Make final image
FROM scratch
COPY --from=mosgarage_app / /

ARG USERNAME=mosgarage
ARG mosgarage_HOME=/usr/local/mosgarage-home

ENV mosgarage_HOME=${mosgarage_HOME}
ENV PYTHONIOENCODING=utf-8
ENV PATH="/usr/local/go/bin:${PATH}"
ENV PATH="${mosgarage_HOME}/mosgarage:${PATH}"
USER ${USERNAME}
WORKDIR ${mosgarage_HOME}
ENV VERSION="<placeholder>"

ENTRYPOINT ["bash", "/usr/local/scripts/entry.sh"]
CMD ["help"]