name: Build Many Containers

on:
  workflow_dispatch:
    inputs:
      servers:
        required: true
        type: string

  workflow_call:
    inputs:
      servers:
        required: true
        type: string

jobs:
  get-server-list:
    name: Get Server List

    runs-on: ubuntu-latest

    outputs:
      servers: ${{ steps.set-servers.outputs.servers }}

    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Set server list
        id: set-servers
        run: |
          bun -e "console.log(JSON.stringify(\"${{ inputs.servers }}\".split(',').map(s => s.trim()).filter(Boolean)))" > server-list.json
          echo "server-list.json contents:"
          cat server-list.json
          echo "servers=$(cat server-list.json)" >> $GITHUB_OUTPUT

  build-all:
    name: Build All Containers

    needs: get-server-list

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        server: ${{ fromJson(needs.get-server-list.outputs.servers) }}
      fail-fast: false

    uses: ./.github/workflows/build-single.yml
    with:
      server: ${{ matrix.server }}
    secrets: inherit
